---
version: '3.4'
services:

  bootnode:
    build:
      context: besu
      args:
        BESU_VERSION: ${BESU_VERSION}
    image: sample-network/besu:${BESU_VERSION}
    environment:
      - BESU_PUBLIC_KEY_DIRECTORY=${BESU_PUBLIC_KEY_DIRECTORY}
      - LOG4J_CONFIGURATION_FILE=/config/log-config.xml
    entrypoint: /opt/besu/bootnode_start.sh
    command: &base_options [
      "--config-file=/config/config.toml",
      "--genesis-file=/config/genesis.json",
      "--node-private-key-file=/opt/besu/keys/key",
      "--rpc-http-api=WEB3,ETH,NET,EEA,ADMIN,${BESU_CONS_API}",
      "--rpc-ws-api=WEB3,ETH,NET,EEA,ADMIN,${BESU_CONS_API}"]
    volumes:
      - public-keys:${BESU_PUBLIC_KEY_DIRECTORY}
      - ./config/besu/config.toml:/config/config.toml
      - ./config/besu/log-config.xml:/config/log-config.xml
      - ./logs/besu:/var/log/
      - ./config/besu/${BESU_CONS_ALGO}Genesis.json:/config/genesis.json
      - ./config/besu/networkFiles/bootnode/keys:/opt/besu/keys

  validator2:
    image: sample-network/besu:${BESU_VERSION}
    environment:
      - BESU_PUBLIC_KEY_DIRECTORY=${BESU_PUBLIC_KEY_DIRECTORY}
      - LOG4J_CONFIGURATION_FILE=/config/log-config.xml
    command: *base_options
    volumes:
      - public-keys:${BESU_PUBLIC_KEY_DIRECTORY}
      - ./config/besu/config.toml:/config/config.toml
      - ./config/besu/log-config.xml:/config/log-config.xml
      - ./logs/besu:/var/log/
      - ./config/besu/${BESU_CONS_ALGO}Genesis.json:/config/genesis.json
      - ./config/besu/networkFiles/validator2/keys:/opt/besu/keys
    depends_on:
      - bootnode

  validator3:
    image: sample-network/besu:${BESU_VERSION}
    environment:
      - BESU_PUBLIC_KEY_DIRECTORY=${BESU_PUBLIC_KEY_DIRECTORY}
      - LOG4J_CONFIGURATION_FILE=/config/log-config.xml
    command: *base_options
    volumes:
      - public-keys:${BESU_PUBLIC_KEY_DIRECTORY}
      - ./config/besu/config.toml:/config/config.toml
      - ./config/besu/log-config.xml:/config/log-config.xml
      - ./logs/besu:/var/log/
      - ./config/besu/${BESU_CONS_ALGO}Genesis.json:/config/genesis.json
      - ./config/besu/networkFiles/validator3/keys:/opt/besu/keys
    depends_on:
      - bootnode

  validator4:
    image: sample-network/besu:${BESU_VERSION}
    environment:
      - BESU_PUBLIC_KEY_DIRECTORY=${BESU_PUBLIC_KEY_DIRECTORY}
      - LOG4J_CONFIGURATION_FILE=/config/log-config.xml
    command: *base_options
    volumes:
      - public-keys:${BESU_PUBLIC_KEY_DIRECTORY}
      - ./config/besu/config.toml:/config/config.toml
      - ./config/besu/log-config.xml:/config/log-config.xml
      - ./logs/besu:/var/log/
      - ./config/besu/${BESU_CONS_ALGO}Genesis.json:/config/genesis.json
      - ./config/besu/networkFiles/validator4/keys:/opt/besu/keys
    depends_on:
      - bootnode

  rpcnode:
    image: sample-network/besu:${BESU_VERSION}
    environment:
      - BESU_PUBLIC_KEY_DIRECTORY=${BESU_PUBLIC_KEY_DIRECTORY}
      - LOG4J_CONFIGURATION_FILE=/config/log-config.xml
    command: *base_options
    volumes:
      - public-keys:${BESU_PUBLIC_KEY_DIRECTORY}
      - ./config/besu/config.toml:/config/config.toml
      - ./config/besu/log-config.xml:/config/log-config.xml
      - ./logs/besu:/var/log/
      - ./config/besu/${BESU_CONS_ALGO}Genesis.json:/config/genesis.json
      - ./config/besu/networkFiles/rpcnode/keys:/opt/besu/keys
    depends_on:
      - bootnode
    ports:
      - 8545:8545/tcp

  ethsignerProxy:
    image: pegasyseng/ethsigner:latest
    command: [
      "--chain-id=2018",
      "--http-listen-host=0.0.0.0",
      "--downstream-http-port=8545",
      "--downstream-http-host=rpcnode",
      "file-based-signer",
      "-k",
      "/opt/ethsigner/keyfile",
      "-p",
      "/opt/ethsigner/passwordfile"
    ]
    volumes:
      - ./config/ethsigner/password:/opt/ethsigner/passwordfile
      - ./config/ethsigner/key:/opt/ethsigner/keyfile
    depends_on:
      - bootnode
      - rpcnode
    ports:
      - 18545:8545/tcp

  explorer:
    build: block-explorer-light
    image: sample-network/block-explorer-light:${BESU_VERSION}
    depends_on:
      - rpcnode
    ports:
      - 25000:80/tcp

  prometheus:
    image: "prom/prometheus"
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090/tcp

  grafana:
    image: "grafana/grafana"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
    volumes:
      - ./config/grafana/provisioning/:/etc/grafana/provisioning/
      - grafana:/var/lib/grafana
    ports:
      - 3000:3000/tcp

  redis:
    image: redis:alpine

  elasticsearch:
    build: ./elk/lasticsearch
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "http.host=0.0.0.0"
      - "transport.host=127.0.0.1"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK

  kibana:
    image: docker.elastic.co/kibana/kibana:7.8.0
    environment:
      ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
      XPACK_MONITORING_ENABLED: "true"
      XPACK_MONITORING_COLLECTION_ENABLED: "true"
      SERVER_NAME: "localhost"
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
    ports:
      - 5601:5601/tcp

  logstash:
    build: ./elk/logstash
    environment:
      - ES_HOST=http://elasticsearch:9200
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
      - elasticsearch
    links:
      - redis
      - elasticsearch

  filebeat:
    build: ./elk/filebeat
    environment:
      - ENV_NAME=dev
      - IP_ADDRESS=127.0.0.1
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    links:
      - redis
    volumes:
      - ./logs/besu/:/var/log/besu/



volumes:
  public-keys:

  prometheus:

  grafana:
