---
version: '3.6'

x-besu-def:
  &besu-def
  restart: "on-failure"
  image: quorum-dev-quickstart/besu:${BESU_VERSION:-latest}
  environment:
    - LOG4J_CONFIGURATION_FILE=/config/log-config.xml
  entrypoint: /opt/besu/node_start.sh
  command: [
    "--config-file=/config/config.toml",
    "--genesis-file=/config/genesis.json",
    "--node-private-key-file=/opt/besu/keys/key",
    "--min-gas-price=0",
    "--rpc-http-api=EEA,WEB3,ETH,NET,{% if privacy %}PRIV,{% endif %}PERM,${BESU_CONS_API:-ibft}",
    "--rpc-ws-api=EEA,WEB3,ETH,NET,{% if privacy %}PRIV,{% endif %}PERM,${BESU_CONS_API:-ibft}"{% if privacy %},
    "--privacy-onchain-groups-enabled=${PRIVACY_ONCHAIN_GROUPS_ENABLED:-false}"{% endif %} ]
  mem_limit: 2048m

x-cakeshop-def:
  &cakeshop-def
  image: quorumengineering/cakeshop:0.11.0
  expose:
    - 8999
  restart: "no"
  healthcheck:
    test: ["CMD", "wget", "--spider", "--proxy=off", "http://localhost:8999/actuator/health"]
    interval: 5s
    timeout: 5s
    retries: 20
    start_period: 5s
  entrypoint:
    - /bin/sh
    - -c
    - |
      rm -rf /data/cakeshop/local
      mkdir -p /data/cakeshop/local
      cp /quorum/application.properties /data/cakeshop/local/application.properties
      cp /quorum/5nodes_besu_docker.json /data/cakeshop/local/5nodes.json
      java -Xms128M -Xmx128M -Dcakeshop.config.dir=/data/cakeshop -Dlogging.path=/data/logs/cakeshop -jar /opt/cakeshop/cakeshop.war
      ;;

{% if privacy %}
x-orion-def:
  &orion-def
  image: "pegasyseng/orion:develop"
  command: ["/config/orion.conf"]
  mem_limit: 1024m
{% endif %}

services:
  {% if privacy %}
  orion1:
    << : *orion-def
    environment:
      - ORION_OTHERNODES=http://orion2:8080/,http://orion3:8080/
      - ORION_NODEURL=http://orion1:8080
      - ORION_CLIENTURL=http://orion1:8888
      - LOG4J_CONFIGURATION_FILE=/config/log-config.xml
    volumes:
      - ./config/orion/orion.conf:/config/orion.conf
      - ./config/orion/networkFiles/orion1:/keys/
      - ./logs/orion:/var/log/
      - ./config/orion/log-config.xml:/config/log-config.xml
    networks:
      sample:
        ipv4_address: 172.16.239.26

  orion2:
    << : *orion-def
    environment:
      - ORION_OTHERNODES=http://orion1:8080/,http://orion3:8080/
      - ORION_NODEURL=http://orion2:8080
      - ORION_CLIENTURL=http://orion2:8888
      - LOG4J_CONFIGURATION_FILE=/config/log-config.xml
    volumes:
      - ./config/orion/orion.conf:/config/orion.conf
      - ./config/orion/networkFiles/orion2:/keys/
      - ./logs/orion:/var/log/
      - ./config/orion/log-config.xml:/config/log-config.xml
    networks:
      sample:
        ipv4_address: 172.16.239.27

  orion3:
    << : *orion-def
    environment:
      - ORION_OTHERNODES=http://orion2:8080/,http://orion1:8080/
      - ORION_NODEURL=http://orion3:8080
      - ORION_CLIENTURL=http://orion3:8888
      - LOG4J_CONFIGURATION_FILE=/config/log-config.xml
    volumes:
      - ./config/orion/orion.conf:/config/orion.conf
      - ./config/orion/networkFiles/orion3:/keys/
      - ./logs/orion:/var/log/
      - ./config/orion/log-config.xml:/config/log-config.xml
    networks:
      sample:
        ipv4_address: 172.16.239.28
{% endif %}

  bootnode:
    << : *besu-def
    build:
      context: besu/.
      args:
        BESU_VERSION: ${BESU_VERSION:-latest}
    entrypoint: /opt/besu/bootnode_start.sh
    volumes:
      - public-keys:/opt/besu/public-keys/
      - ./config/besu/config.toml:/config/config.toml
      - ./config/besu/permissions_config.toml:/config/permissions_config.toml
      - ./config/besu/log-config.xml:/config/log-config.xml
      - ./logs/besu:/var/log/
      - ./config/besu/${BESU_CONS_ALGO:-ibft2}Genesis.json:/config/genesis.json
      - ./config/besu/networkFiles/bootnode/keys:/opt/besu/keys
    networks:
      sample:
        ipv4_address: 172.16.239.11

  validator2:
    << : *besu-def
    volumes:
      - public-keys:/opt/besu/public-keys/
      - ./config/besu/config.toml:/config/config.toml
      - ./config/besu/permissions_config.toml:/config/permissions_config.toml
      - ./config/besu/log-config.xml:/config/log-config.xml
      - ./logs/besu:/var/log/
      - ./config/besu/${BESU_CONS_ALGO:-ibft2}Genesis.json:/config/genesis.json
      - ./config/besu/networkFiles/validator2/keys:/opt/besu/keys
    depends_on:
      - bootnode
    networks:
      sample:
        ipv4_address: 172.16.239.12

  validator3:
    << : *besu-def
    volumes:
      - public-keys:/opt/besu/public-keys/
      - ./config/besu/config.toml:/config/config.toml
      - ./config/besu/permissions_config.toml:/config/permissions_config.toml
      - ./config/besu/log-config.xml:/config/log-config.xml
      - ./logs/besu:/var/log/
      - ./config/besu/${BESU_CONS_ALGO:-ibft2}Genesis.json:/config/genesis.json
      - ./config/besu/networkFiles/validator3/keys:/opt/besu/keys
    depends_on:
      - bootnode
    networks:
      sample:
        ipv4_address: 172.16.239.13

  validator4:
    << : *besu-def
    volumes:
      - public-keys:/opt/besu/public-keys/
      - ./config/besu/config.toml:/config/config.toml
      - ./config/besu/permissions_config.toml:/config/permissions_config.toml
      - ./config/besu/log-config.xml:/config/log-config.xml
      - ./logs/besu:/var/log/
      - ./config/besu/${BESU_CONS_ALGO:-ibft2}Genesis.json:/config/genesis.json
      - ./config/besu/networkFiles/validator4/keys:/opt/besu/keys
    depends_on:
      - bootnode
    networks:
      sample:
        ipv4_address: 172.16.239.14

  rpcnode:
    << : *besu-def
    volumes:
      - public-keys:/opt/besu/public-keys/
      - ./config/besu/config.toml:/config/config.toml
      - ./config/besu/permissions_config.toml:/config/permissions_config.toml
      - ./config/besu/log-config.xml:/config/log-config.xml
      - ./logs/besu:/var/log/
      - ./config/besu/${BESU_CONS_ALGO:-ibft2}Genesis.json:/config/genesis.json
      - ./config/besu/networkFiles/rpcnode/keys:/opt/besu/keys
    depends_on:
      - bootnode
    ports:
      - 8545:8545/tcp
    networks:
      sample:
        ipv4_address: 172.16.239.15

  ethsignerProxy:
    image: pegasyseng/ethsigner:latest
    command: [
      "--chain-id=2018",
      "--http-listen-host=0.0.0.0",
      "--downstream-http-port=8545",
      "--downstream-http-host=rpcnode",
      "file-based-signer",
      "-k",
      "/opt/ethsigner/keyfile",
      "-p",
      "/opt/ethsigner/passwordfile"
    ]
    volumes:
      - ./config/ethsigner/password:/opt/ethsigner/passwordfile
      - ./config/ethsigner/key:/opt/ethsigner/keyfile
    depends_on:
      - bootnode
      - rpcnode
    ports:
      - 18545:8545/tcp
    networks:
      sample:
        ipv4_address: 172.16.239.20

{% if privacy %}
  private_node1:
    << : *besu-def
    command: [
      "--config-file=/config/config.toml",
      "--genesis-file=/config/genesis.json",
      "--node-private-key-file=/opt/besu/keys/key",
      "--rpc-http-api=EEA,WEB3,ETH,NET,PRIV,PERM,${BESU_CONS_API:-ibft}",
      "--rpc-ws-api=EEA,WEB3,ETH,NET,PRIV,PERM,${BESU_CONS_API:-ibft}",
      "--min-gas-price=0",
      "--privacy-enabled",
      "--privacy-url=http://orion1:8888",
      "--privacy-public-key-file=/config/orion/orion.pub",
      "--privacy-onchain-groups-enabled=${PRIVACY_ONCHAIN_GROUPS_ENABLED:-false}"]
    volumes:
      - public-keys:/opt/besu/public-keys/
      - ./config/besu/config.toml:/config/config.toml
      - ./config/besu/permissions_config.toml:/config/permissions_config.toml
      - ./config/besu/log-config.xml:/config/log-config.xml
      - ./logs/besu:/var/log/
      - ./config/besu/${BESU_CONS_ALGO:-ibft2}Genesis.json:/config/genesis.json
      - ./config/besu/networkFiles/node1/keys:/opt/besu/keys
      - ./config/orion/networkFiles/orion1/nodeKey.pub:/config/orion/orion.pub
    depends_on:
      - bootnode
      - orion1
    ports:
      - 20000:8545/tcp
      - 20001:8546/tcp
    networks:
      sample:
        ipv4_address: 172.16.239.16

  private_node2:
    << : *besu-def
    command: [
      "--config-file=/config/config.toml",
      "--genesis-file=/config/genesis.json",
      "--node-private-key-file=/opt/besu/keys/key",
      "--rpc-http-api=EEA,WEB3,ETH,NET,PRIV,PERM,${BESU_CONS_API:-ibft}",
      "--rpc-ws-api=EEA,WEB3,ETH,NET,PRIV,PERM,${BESU_CONS_API:-ibft}",
      "--min-gas-price=0",
      "--privacy-enabled",
      "--privacy-url=http://orion2:8888",
      "--privacy-public-key-file=/config/orion/orion.pub",
      "--privacy-onchain-groups-enabled=${PRIVACY_ONCHAIN_GROUPS_ENABLED:-false}"]
    volumes:
      - public-keys:/opt/besu/public-keys/
      - ./config/besu/config.toml:/config/config.toml
      - ./config/besu/permissions_config.toml:/config/permissions_config.toml
      - ./config/besu/log-config.xml:/config/log-config.xml
      - ./logs/besu:/var/log/
      - ./config/besu/${BESU_CONS_ALGO:-ibft2}Genesis.json:/config/genesis.json
      - ./config/besu/networkFiles/node2/keys:/opt/besu/keys
      - ./config/orion/networkFiles/orion2/nodeKey.pub:/config/orion/orion.pub
    depends_on:
      - bootnode
      - orion2
    ports:
      - 20002:8545/tcp
      - 20003:8546/tcp
    networks:
      sample:
        ipv4_address: 172.16.239.17

  private_node3:
    << : *besu-def
    command: [
      "--config-file=/config/config.toml",
      "--genesis-file=/config/genesis.json",
      "--node-private-key-file=/opt/besu/keys/key",
      "--rpc-http-api=EEA,WEB3,ETH,NET,PRIV,PERM,${BESU_CONS_API:-ibft}",
      "--rpc-ws-api=EEA,WEB3,ETH,NET,PRIV,PERM,${BESU_CONS_API:-ibft}",
      "--min-gas-price=0",
      "--privacy-enabled",
      "--privacy-url=http://orion3:8888",
      "--privacy-public-key-file=/config/orion/orion.pub",
      "--privacy-onchain-groups-enabled=${PRIVACY_ONCHAIN_GROUPS_ENABLED:-false}"]
    volumes:
      - public-keys:/opt/besu/public-keys/
      - ./config/besu/config.toml:/config/config.toml
      - ./config/besu/permissions_config.toml:/config/permissions_config.toml
      - ./config/besu/log-config.xml:/config/log-config.xml
      - ./logs/besu:/var/log/
      - ./config/besu/${BESU_CONS_ALGO:-ibft2}Genesis.json:/config/genesis.json
      - ./config/besu/networkFiles/node3/keys:/opt/besu/keys
      - ./config/orion/networkFiles/orion3/nodeKey.pub:/config/orion/orion.pub
    depends_on:
      - bootnode
      - orion3
    ports:
      - 20004:8545/tcp
      - 20005:8546/tcp
    networks:
      sample:
        ipv4_address: 172.16.239.18
{% endif %}

  explorer:
    build: block-explorer-light/.
    image: quorum-dev-quickstart/block-explorer-light:develop
    depends_on:
      - rpcnode
    ports:
      - 25000:80/tcp
    networks:
      sample:
        ipv4_address: 172.16.239.31

  prometheus:
    image: "prom/prometheus"
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090/tcp
    networks:
      sample:
        ipv4_address: 172.16.239.32

  grafana:
    image: "grafana/grafana"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
    volumes:
      - ./config/grafana/provisioning/:/etc/grafana/provisioning/
      - grafana:/var/lib/grafana
    ports:
      - 3000:3000/tcp
    networks:
      sample:
        ipv4_address: 172.16.239.33

  cakeshop:
    << : *cakeshop-def
    hostname: cakeshop
    ports:
      - "8999:8999"
    volumes:
      - cakeshop:/data
      - ./config/cakeshop:/quorum
    networks:
      quorum-examples-net:
        ipv4_address: 172.16.239.34

volumes:
  public-keys:

  prometheus:

  grafana:

  cakeshop:

networks:
  sample:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.239.0/24
