---
version: '3.6'


{% if monitoring == "splunk" %}
x-splunk-def:
  &splunk-def
  image: splunk/splunk:8.2
  container_name: splunk
  environment:
    - SPLUNK_START_ARGS=--accept-license
    - SPLUNK_HEC_TOKEN=11111111-1111-1111-1111-1111111111113
    - SPLUNK_PASSWORD=quickstart
    - SPLUNK_APPS_URL=https://github.com/splunkdlt/splunk-app-quorum/releases/download/1.0.6/splunk_app_quorum-v1.0.6.tgz
  ports:
    - 8000:8000
    - 8088:8088
  healthcheck:
    test: ['CMD', 'curl', '-f', 'http://localhost:8000']
    interval: 5s
    timeout: 5s
    retries: 20
  volumes:
    - ./splunk/splunk.yml:/tmp/defaults/default.yml
    - splunk:/opt/splunk/var

x-otelcollector-def:
  &otelcollector-def
  image: quay.io/signalfx/splunk-otel-collector:0.26.0
  container_name: otelcollector
  depends_on:
    - splunk
  command:
    - --config
    - /etc/otel/config.yaml
  volumes:
    - ./splunk/otel-collector-config.yml:/etc/otel/config.yaml
    - /var/log:/var/log
    - ./logs/tessera:/var/log-tessera
    - ./logs/quorum:/var/log-quorum
  environment:
    - SPLUNK_HEC_TOKEN=11111111-1111-1111-1111-1111111111113
    - SPLUNK_ACCESS_TOKEN=disable # You can use this option to send data to Splunk Cloud.
    - SPLUNK_REALM=disable # You can use this option to send data to Splunk Cloud.

x-ethlogger-def:
  &ethlogger-def
  image: ghcr.io/splunkdlt/ethlogger:3.0.1
  container_name: ethlogger
  environment:
    - COLLECT_PEER_INFO=true
    - COLLECT_PENDING_TX=true
    - ETH_RPC_URL=http://rpcnode:8545
    - NETWORK_NAME=quickstart
    - START_AT_BLOCK=latest
    - SPLUNK_HEC_URL=https://splunk:8088
    - SPLUNK_HEC_TOKEN=11111111-1111-1111-1111-1111111111113
    - SPLUNK_EVENTS_INDEX=ledger
    - SPLUNK_METRICS_INDEX=metrics
    - SPLUNK_INTERNAL_INDEX=metrics
    - SPLUNK_HEC_REJECT_INVALID_CERTS=false
    - ABI_DIR=/app/abis
    - DEBUG=ethlogger:platforms,ethlogger:eth
  volumes:
    - ethlogger:/app
    - ./smart_contracts/contracts:/app/abis
  depends_on:
    - splunk
  restart: unless-stopped

{% endif %}

x-quorum-def:
  &quorum-def
  restart: "on-failure"
  image: quorumengineering/quorum:${QUORUM_VERSION:-2.7.0}
  expose:
    - 30303
    - 8545
    - 9545
  labels:
    com.quorum.consensus: ${QUORUM_CONSENSUS:-istanbul}
  healthcheck:
    test: ["CMD", "wget", "--spider", "--proxy", "off", "http://localhost:8545"]
    interval: 3s
    timeout: 3s
    retries: 10
    start_period: 5s
  environment:
    - QUORUM_CONSENSUS=${QUORUM_CONS_ALGO:-istanbul}
  entrypoint:
    - /bin/sh
    - -c
    - |
      CONSENSUS_ARGS="--istanbul.blockperiod 5 --mine --minerthreads 1 --miner.gasprice 0 --emitcheckpoints"
      if [ "raft" == $$QUORUM_CONSENSUS ];
      then
        CONSENSUS_ARGS="--raft --raftblocktime 300 --raftport 53000"
      fi

      mkdir -p /var/log/quorum/;
      mkdir -p /data;
      cp -r /quorum/* /data;
      geth --datadir=/data init /config/genesis.json;
      cp /config/keys/accountkey /data/keystore/key;
      cp /config/keys/nodekey /data/geth/nodekey;
      geth \
      --datadir /data \
      --nodiscover \
      --permissioned \
      --verbosity 5 \
      $$CONSENSUS_ARGS \
      --syncmode full --nousb \
      --metrics --pprof --pprofaddr 0.0.0.0 --pprofport 9545 \
      --networkid $${QUORUM_NETWORK_ID:-1337} \
      --rpc --rpcaddr 0.0.0.0 --rpcport 8545 --rpccorsdomain "*" --rpcvhosts "*" --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,$$QUORUM_CONSENSUS \
      --port 30303 \
      --identity node$${NODE_ID}-$$QUORUM_CONSENSUS \
      --unlock 0 \
      --allow-insecure-unlock \
      --password /config/passwords.txt \
      &> /var/log/quorum/geth-$$HOSTNAME-$$(hostname -i).log | tee -a /var/log/quorum/geth-$$HOSTNAME-$$(hostname -i).log


x-quorum-member-def:
  &quorum-member-def
  restart: "on-failure"
  image: quorumengineering/quorum:${QUORUM_VERSION:-2.7.0}
  expose:
    - 30303
    - 8545
    - 9545
  labels:
    com.quorum.consensus: ${QUORUM_CONSENSUS:-istanbul}
  healthcheck:
    test: ["CMD", "wget", "--spider", "--proxy", "off", "http://localhost:8545"]
    interval: 3s
    timeout: 3s
    retries: 10
    start_period: 5s
  environment:
    - QUORUM_CONSENSUS=${QUORUM_CONS_ALGO:-istanbul}
  entrypoint:
    - /bin/sh
    - -c
    - |
      {%if privacy %}
      for i in $$(seq 1 100)
      do
        set -e
        if [ "I'm up!" == "$$(wget --timeout 10 -qO- --proxy off 172.16.239.2$${NODE_ID}:9000/upcheck)" ];
          then break
        else
          echo "Waiting for Tessera..."
          sleep 10
        fi
      done
      {% endif %}

      CONSENSUS_ARGS="--istanbul.blockperiod 5 --mine --minerthreads 1 --miner.gasprice 0 --emitcheckpoints"
      if [ "raft" == $$QUORUM_CONSENSUS ];
      then
        CONSENSUS_ARGS="--raft --raftblocktime 300 --raftport 53000"
      fi

      mkdir -p /var/log/quorum/;
      mkdir -p /data/dd;
      cp -r /quorum/* /data/dd/;
      geth --datadir=/data/dd init /config/genesis.json;
      cp /config/keys/accountkey /data/dd/keystore/key;
      cp /config/keys/nodekey /data/dd/geth/nodekey;
      geth \
      --datadir /data/dd \
      --nodiscover \
      --permissioned \
      --verbosity 5 \
      $$CONSENSUS_ARGS \
      --syncmode full --nousb \
      --metrics --pprof --pprofaddr 0.0.0.0 --pprofport 9545 \
      --networkid $${QUORUM_NETWORK_ID:-1337} \
      --rpc --rpcaddr 0.0.0.0 --rpcport 8545 --rpccorsdomain "*" --rpcvhosts "*" --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,$$QUORUM_CONSENSUS \
      --ws --wsaddr 0.0.0.0 --wsport 8546 --wsorigins "*" --wsapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,$$QUORUM_CONSENSUS \
      --port 30303 \
      --identity node$${NODE_ID}-$$QUORUM_CONSENSUS \
      --ptm.timeout 5 --ptm.url $${QUORUM_PTM_URL} --ptm.http.writebuffersize 4096 --ptm.http.readbuffersize 4096 --ptm.tls.mode off \
      --unlock 0 \
      --allow-insecure-unlock \
      --password /config/passwords.txt \
      &> /var/log/quorum/geth-$$(hostname -i).log | tee -a /var/log/quorum/geth-$$(hostname -i).log



{% if privacy %}
x-tessera-def:
  &tessera-def
  image: quorumengineering/tessera:${QUORUM_TESSERA_VERSION:-0.10.5}
  expose:
    - 9000
    - 9080
    - 9101
  restart: "no"
  healthcheck:
    test: ["CMD", "wget", "--spider", "--proxy", "off", "http://localhost:9000/upcheck"]
    interval: 3s
    timeout: 3s
    retries: 20
    start_period: 5s
  entrypoint:
    - /bin/sh
    - -c
    - |
      mkdir -p /var/log/tessera/;
      mkdir -p /data/tm/;
      cp /config/keys/tm.* /data/tm/ ;

          cat <<EOF > /data/tm/tessera-config-09.json
          {
            "useWhiteList": false,
            "jdbc": {
              "username": "sa",
              "password": "",
              "url": "jdbc:h2:./data/tm/db;MODE=Oracle;TRACE_LEVEL_SYSTEM_OUT=0",
              "autoCreateTables": true
            },
            "serverConfigs":[
            {
              "app":"ThirdParty",
              "enabled": true,
              "serverAddress": "http://$$(hostname -i):9080",
              "communicationType" : "REST"
            },
            {
              "app":"Q2T",
              "enabled": true,
              "serverAddress": "http://$$(hostname -i):9101",
              "sslConfig": {
                "tls": "OFF"
              },
              "communicationType" : "REST"
            },
            {
              "app":"P2P",
              "enabled": true,
              "serverAddress": "http://$$(hostname -i):9000",
              "sslConfig": {
                "tls": "OFF"
              },
              "communicationType" : "REST"
            }
            ],
            "peer": [
               {
                   "url": "http://member1tessera:9000"
               },
               {
                   "url": "http://member2tessera:9000"
               },
               {
                   "url": "http://member3tessera:9000"
               }
            ],
            "keys": {
              "passwords": [],
              "keyData": [
                {
                  "config": $$(cat /data/tm/tm.key),
                  "publicKey": "$$(cat /data/tm/tm.pub)"
                }
              ]
            },
            "alwaysSendTo": []
          }
      EOF
          cat /data/tm/tessera-config-09.json
          java -Xms128M -Xmx128M -jar /tessera/tessera-app.jar -configfile /data/tm/tessera-config-09.json &> /var/log/tessera/tessera-$$HOSTNAME.log | tee -a /var/log/tessera/tessera-$$HOSTNAME.log

{% endif %}

x-cakeshop-def:
  &cakeshop-def
  image: quorumengineering/cakeshop:${QUORUM_CAKESHOP_VERSION:-0.11.0}
  expose:
    - 8999
  restart: "no"
  healthcheck:
    test: ["CMD", "wget", "--spider", "--proxy=off", "http://localhost:8999/actuator/health"]
    interval: 5s
    timeout: 5s
    retries: 20
    start_period: 5s
  entrypoint:
    - /bin/sh
    - -c
    - |
      rm -rf /data/cakeshop/local
      mkdir -p /data/cakeshop/local
      cp /quorum/application.properties /data/cakeshop/local/application.properties
{% if privacy %}
      cp /quorum/8nodes_quorum_docker.json /data/cakeshop/local/seednodes.json
{% else %}
      cp /quorum/5nodes_quorum_docker.json /data/cakeshop/local/seednodes.json
{% endif %}
      java -Xms128M -Xmx128M -Dcakeshop.config.dir=/data/cakeshop -Dlogging.path=/data/logs/cakeshop -jar /opt/cakeshop/cakeshop.war
      ;;


{% if monitoring == "elk" %}
x-redis-def:
  &redis-def
  image: redis:alpine

x-elasticsearch-def:
  &elasticsearch-def
  build: ./elasticsearch
  environment:
    - bootstrap.memory_lock=true
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    - "http.host=0.0.0.0"
    - "transport.host=127.0.0.1"
  ulimits:
    memlock:
      soft: -1
      hard: -1
    nofile:
      soft: 65536
      hard: 65536
  cap_add:
    - IPC_LOCK

x-kibana-def:
  &kibana-def
  image: docker.elastic.co/kibana/kibana:7.9.3
  environment:
    ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
    XPACK_MONITORING_ENABLED: "true"
    XPACK_MONITORING_COLLECTION_ENABLED: "true"
    SERVER_NAME: "localhost"
  depends_on:
    - elasticsearch
  links:
    - elasticsearch
  ports:
    - 5601:5601/tcp

x-logstash-def:
  &logstash-def
  build: ./logstash
  environment:
    - ES_HOST=http://elasticsearch:9200
    - REDIS_HOST=redis
    - REDIS_PORT=6379
  depends_on:
    - redis
    - elasticsearch
  links:
    - redis
    - elasticsearch

x-filebeat-def:
  &filebeat-def
  build: ./filebeat
  environment:
    - ENV_NAME=dev
    - IP_ADDRESS=127.0.0.1
    - REDIS_HOST=redis
    - REDIS_PORT=6379
  depends_on:
    - redis
  links:
    - redis
  volumes:
    - ./logs/quorum/:/var/log/quorum/
    - ./logs/tessera/:/var/log/tessera/

{% endif %}



services:

  validator1:
    << : *quorum-def
    ports:
      - 21001:8545/tcp
      - 30303
      - 9545
    environment:
      - NODE_ID=1
      - PRIVATE_CONFIG=ignore
      - QUORUM_CONSENSUS=${QUORUM_CONS_ALGO:-istanbul}
    volumes:
      - ./config/quorum/passwords.txt:/config/passwords.txt
      - ./config/quorum/${QUORUM_CONS_ALGO:-istanbul}Genesis.json:/config/genesis.json
      - ./config/quorum/support:/quorum
      - ./config/quorum/networkFiles/validator1:/config/keys
      - ./logs/quorum:/var/log/quorum/
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.11

  validator2:
    << : *quorum-def
    ports:
      - 21002:8545/tcp
      - 30303
      - 9545
    environment:
      - NODE_ID=4
      - PRIVATE_CONFIG=ignore
      - QUORUM_CONSENSUS=${QUORUM_CONS_ALGO:-istanbul}
    volumes:
      - ./config/quorum/passwords.txt:/config/passwords.txt
      - ./config/quorum/${QUORUM_CONS_ALGO:-istanbul}Genesis.json:/config/genesis.json
      - ./config/quorum/support:/quorum
      - ./config/quorum/networkFiles/validator2:/config/keys
      - ./logs/quorum:/var/log/quorum/
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.12

  validator3:
    << : *quorum-def
    ports:
      - 21003:8545/tcp
      - 30303
      - 9545
    environment:
      - NODE_ID=4
      - PRIVATE_CONFIG=ignore
      - QUORUM_CONSENSUS=${QUORUM_CONS_ALGO:-istanbul}
    volumes:
      - ./config/quorum/passwords.txt:/config/passwords.txt
      - ./config/quorum/${QUORUM_CONS_ALGO:-istanbul}Genesis.json:/config/genesis.json
      - ./config/quorum/support:/quorum
      - ./config/quorum/networkFiles/validator3:/config/keys
      - ./logs/quorum:/var/log/quorum/
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.13

  validator4:
    << : *quorum-def
    ports:
      - 22004:8545/tcp
      - 30303
      - 9545
    environment:
      - NODE_ID=4
      - PRIVATE_CONFIG=ignore
      - QUORUM_CONSENSUS=${QUORUM_CONS_ALGO:-istanbul}
    volumes:
      - ./config/quorum/passwords.txt:/config/passwords.txt
      - ./config/quorum/${QUORUM_CONS_ALGO:-istanbul}Genesis.json:/config/genesis.json
      - ./config/quorum/support:/quorum
      - ./config/quorum/networkFiles/validator4:/config/keys
      - ./logs/quorum:/var/log/quorum/
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.14

  rpcnode:
    << : *quorum-def
    container_name: rpcnode
    ports:
      - 8545:8545/tcp
      - 8546:8546/tcp
      - 30303
      - 9545
    environment:
      - NODE_ID=5
      - PRIVATE_CONFIG=ignore
      - QUORUM_CONSENSUS=${QUORUM_CONS_ALGO:-istanbul}
    volumes:
      - ./config/quorum/passwords.txt:/config/passwords.txt
      - ./config/quorum/${QUORUM_CONS_ALGO:-istanbul}Genesis.json:/config/genesis.json
      - ./config/quorum/support:/quorum
      - ./config/quorum/networkFiles/rpcnode:/config/keys
      - ./logs/quorum:/var/log/quorum/
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.15

{% if privacy %}
  member1tessera:
    << : *tessera-def
    ports:
      - 9081:9080
    environment:
      - TESSERA_CONFIG_TYPE="-09"
      - NODE_ID=6
    volumes:
      - ./config/quorum/networkFiles/member1:/config/keys
      - member1volume:/data
      - ./logs/tessera:/var/log/tessera/
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.26

  member1quorum:
    << : *quorum-member-def
    ports:
      - 20000:8545/tcp
      - 20001:8546/tcp
      - 30303
      - 9545
    depends_on:
      - member1tessera
    environment:
      - NODE_ID=6
      - QUORUM_CONSENSUS=${QUORUM_CONS_ALGO:-istanbul}
      - QUORUM_PTM_URL=http://member1tessera:9101
    volumes:
      - ./config/quorum/passwords.txt:/config/passwords.txt
      - ./config/quorum/${QUORUM_CONS_ALGO:-istanbul}Genesis.json:/config/genesis.json
      - ./config/quorum/support:/quorum
      - ./config/quorum/networkFiles/member1:/config/keys
      - member1volume:/data
      - ./logs/quorum:/var/log/quorum/
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.16

  member2tessera:
    << : *tessera-def
    ports:
      - 9082:9080
    environment:
      - TESSERA_CONFIG_TYPE="-09"
      - NODE_ID=7
    volumes:
      - ./config/quorum/networkFiles/member2:/config/keys
      - member2volume:/data
      - ./logs/tessera:/var/log/tessera/
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.27

  member2quorum:
    << : *quorum-member-def
    ports:
      - 20002:8545/tcp
      - 20003:8546/tcp
      - 30303
      - 9545
    depends_on:
      - member2tessera
    environment:
      - NODE_ID=7
      - QUORUM_CONSENSUS=${QUORUM_CONS_ALGO:-istanbul}
      - QUORUM_PTM_URL=http://member2tessera:9101
    volumes:
      - ./config/quorum/passwords.txt:/config/passwords.txt
      - ./config/quorum/${QUORUM_CONS_ALGO:-istanbul}Genesis.json:/config/genesis.json
      - ./config/quorum/support:/quorum
      - ./config/quorum/networkFiles/member2:/config/keys
      - member2volume:/data
      - ./logs/quorum:/var/log/quorum/
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.17

  member3tessera:
    << : *tessera-def
    ports:
      - 9083:9080
    environment:
      - TESSERA_CONFIG_TYPE="-09"
      - NODE_ID=8
    volumes:
      - ./config/quorum/networkFiles/member3:/config/keys
      - member3volume:/data
      - ./logs/tessera:/var/log/tessera/
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.28

  member3quorum:
    << : *quorum-member-def
    ports:
      - 20004:8545/tcp
      - 20005:8546/tcp
      - 30303
      - 9545
    depends_on:
      - member3tessera
    environment:
      - NODE_ID=8
      - QUORUM_CONSENSUS=${QUORUM_CONS_ALGO:-istanbul}
      - QUORUM_PTM_URL=http://member3tessera:9101
    volumes:
      - ./config/quorum/passwords.txt:/config/passwords.txt
      - ./config/quorum/${QUORUM_CONS_ALGO:-istanbul}Genesis.json:/config/genesis.json
      - ./config/quorum/support:/quorum
      - ./config/quorum/networkFiles/member3:/config/keys
      - member3volume:/data
      - ./logs/quorum:/var/log/quorum/
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.18

{% endif %}

  cakeshop:
    << : *cakeshop-def
    hostname: cakeshop
    ports:
      - "8999:8999"
    volumes:
      - cakeshop:/data
      - ./config/cakeshop:/quorum
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.30

  explorer:
    build: block-explorer-light
    image: quorum-dev-quickstart/block-explorer-light:develop
    depends_on:
      - rpcnode
    ports:
      - 25000:80/tcp
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.31

  prometheus:
    image: "prom/prometheus"
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090/tcp
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.32

  grafana:
    image: "grafana/grafana"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
    volumes:
      - ./config/grafana/provisioning/:/etc/grafana/provisioning/
      - grafana:/var/lib/grafana
    ports:
      - 3000:3000/tcp
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.33


{% if monitoring == "elk" %}
  redis:
    << : *redis-def
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.34

  elasticsearch:
    << : *elasticsearch-def
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.35

  kibana:
    << : *kibana-def
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.36

  logstash:
    << : *logstash-def
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.37

  filebeat:
    << : *filebeat-def
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.38

{% elif monitoring == "splunk" %}
  splunk:
    << : *splunk-def
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.35

  otelcollector:
    << : *otelcollector-def
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.36

  ethlogger:
    << : *ethlogger-def
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.37

  cadvisor:
    container_name: cadvisor
    image: gcr.io/cadvisor/cadvisor:v0.39.0
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    command:
      - --docker_only=true
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.38
{% endif %}

networks:
  quorum-dev-quickstart:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.239.0/24

volumes:
  cakeshop:
  member1volume:
  member2volume:
  member3volume:
  splunk:
  ethlogger:
  prometheus:
  grafana:
