---
version: '3.6'

x-quorum-def:
  &quorum-def
  restart: "on-failure"
  image: quorumengineering/quorum:${QUORUM_VERSION:-2.7.0}
  expose:
    - 30303
    - 8545
  labels:
    com.quorum.consensus: ${QUORUM_CONSENSUS:-istanbul}
  healthcheck:
    test: ["CMD", "wget", "--spider", "--proxy", "off", "http://localhost:8545"]
    interval: 3s
    timeout: 3s
    retries: 10
    start_period: 5s
  entrypoint:
    - /bin/sh
    - -c
    - |

      {%if privacy %}
      for i in $$(seq 1 100)
      do
        set -e
        if [ "I'm up!" == "$$(wget --timeout 10 -qO- --proxy off 172.16.239.2$${NODE_ID}:9000/upcheck)" ];
          then break
        else
          echo "Waiting for Tessera..."
          sleep 10
        fi
      done
      {% endif %}

      mkdir /data;
      cp -r /quorum/* /data;
      geth --datadir=/data init /config/genesis.json;
      cp /config/keys/accountkey /data/keystore/key;
      cp /config/keys/nodekey /data/geth/nodekey;
      geth \
      --datadir /data \
      --nodiscover \
      --permissioned \
      --verbosity 5 \
      --istanbul.blockperiod 5 --mine --minerthreads 1 --emitcheckpoints \
      --syncmode full --nousb \
      --networkid ${QUORUM_NETWORK_ID:-10} \
      --rpc --rpcaddr 0.0.0.0 --rpcport 8545 --rpccorsdomain "*" --rpcvhosts "*" --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,${QUORUM_CONS_ALGO:-istanbul} \
      --port 30303 \
      --identity node${NODE_ID}-${QUORUM_CONS_ALGO:-istanbul} \
      --unlock 0 \
      --allow-insecure-unlock \
      --password /config/passwords.txt
      ;

{% if privacy %}
x-tessera-def:
  &tessera-def
  image: quorumengineering/tessera:${QUORUM_TESSERA_VERSION:-0.10.5}
  expose:
    - 9000
    - 9080
  restart: "no"
  healthcheck:
    test: ["CMD-SHELL", "[ -S /data/tm.ipc ] || exit 1"]
    interval: 3s
    timeout: 3s
    retries: 20
    start_period: 5s
  entrypoint:
    - /bin/sh
    - -c
    - |
      mkdir /data;
      cp /config/keys/tm.* /data ;

          cat <<EOF > /data/tessera-config-09.json
          {
            "useWhiteList": false,
            "jdbc": {
              "username": "sa",
              "password": "",
              "url": "jdbc:h2:./data/db;MODE=Oracle;TRACE_LEVEL_SYSTEM_OUT=0",
              "autoCreateTables": true
            },
            "serverConfigs":[
            {
              "app":"ThirdParty",
              "enabled": true,
              "serverAddress": "http://$$(hostname -i):9080",
              "communicationType" : "REST"
            },
            {
              "app":"Q2T",
              "enabled": true,
              "serverAddress": "unix:/data/tm.ipc",
              "communicationType" : "REST"
            },
            {
              "app":"P2P",
              "enabled": true,
              "serverAddress": "http://$$(hostname -i):9000",
              "sslConfig": {
                "tls": "OFF"
              },
              "communicationType" : "REST"
            }
            ],
            "peer": [
               {
                   "url": "http://tessera1:9000"
               },
               {
                   "url": "http://tessera2:9000"
               },
               {
                   "url": "http://tessera3:9000"
               },
               {
                   "url": "http://tessera4:9000"
               },
               {
                   "url": "http://tessera5:9000"
               }
            ],
            "keys": {
              "passwords": [],
              "keyData": [
                {
                  "config": $$(cat /data/tm.key),
                  "publicKey": "$$(cat /data/tm.pub)"
                }
              ]
            },
            "alwaysSendTo": []
          }
      EOF
          cat /data/tessera-config-09.json
          java -Xms128M -Xmx128M -jar /tessera/tessera-app.jar -configfile /data/tessera-config-09.json
{% endif %}

x-cakeshop-def:
  &cakeshop-def
  image: quorumengineering/cakeshop:0.11.0
  expose:
    - 8999
  restart: "no"
  healthcheck:
    test: ["CMD", "wget", "--spider", "--proxy=off", "http://localhost:8999/actuator/health"]
    interval: 5s
    timeout: 5s
    retries: 20
    start_period: 5s
  entrypoint:
    - /bin/sh
    - -c
    - |
      rm -rf /data/cakeshop/local
      mkdir -p /data/cakeshop/local
      cp /quorum/application.properties /data/cakeshop/local/application.properties
{% if privacy %}
      cp /quorum/8nodes_quorum_docker.json /data/cakeshop/local/seednodes.json
{% else %}
      cp /quorum/5nodes_quorum_docker.json /data/cakeshop/local/seednodes.json
{% endif %}
      java -Xms128M -Xmx128M -Dcakeshop.config.dir=/data/cakeshop -Dlogging.path=/data/logs/cakeshop -jar /opt/cakeshop/cakeshop.war
      ;;

services:

  validator1:
    << : *quorum-def
    ports:
      - 21001:8545/tcp
      - 30303
    environment:
      - NODE_ID=1
      - PRIVATE_CONFIG=ignore
      - QUORUM_CONSENSUS=${QUORUM_CONS_ALGO:-istanbul}
    volumes:
      - ./config/quorum/passwords.txt:/config/passwords.txt
      - ./config/quorum/${QUORUM_CONS_ALGO:-istanbul}Genesis.json:/config/genesis.json
      - ./config/quorum/support:/quorum
      - ./config/quorum/networkFiles/validator1:/config/keys
    networks:
      quorum-examples-net:
        ipv4_address: 172.16.239.5

  validator2:
    << : *quorum-def
    ports:
      - 21002:8545/tcp
      - 30303
    environment:
      - NODE_ID=4
      - PRIVATE_CONFIG=ignore
      - QUORUM_CONSENSUS=${QUORUM_CONS_ALGO:-istanbul}
    volumes:
      - ./config/quorum/passwords.txt:/config/passwords.txt
      - ./config/quorum/${QUORUM_CONS_ALGO:-istanbul}Genesis.json:/config/genesis.json
      - ./config/quorum/support:/quorum
      - ./config/quorum/networkFiles/validator2:/config/keys
    networks:
      quorum-examples-net:
        ipv4_address: 172.16.239.6

  validator3:
    << : *quorum-def
    ports:
      - 21003:8545/tcp
      - 30303
    environment:
      - NODE_ID=4
      - PRIVATE_CONFIG=ignore
      - QUORUM_CONSENSUS=${QUORUM_CONS_ALGO:-istanbul}
    volumes:
      - ./config/quorum/passwords.txt:/config/passwords.txt
      - ./config/quorum/${QUORUM_CONS_ALGO:-istanbul}Genesis.json:/config/genesis.json
      - ./config/quorum/support:/quorum
      - ./config/quorum/networkFiles/validator3:/config/keys
    networks:
      quorum-examples-net:
        ipv4_address: 172.16.239.7

  validator4:
    << : *quorum-def
    ports:
      - 22004:8545/tcp
      - 30303
    environment:
      - NODE_ID=4
      - PRIVATE_CONFIG=ignore
      - QUORUM_CONSENSUS=${QUORUM_CONS_ALGO:-istanbul}
    volumes:
      - ./config/quorum/passwords.txt:/config/passwords.txt
      - ./config/quorum/${QUORUM_CONS_ALGO:-istanbul}Genesis.json:/config/genesis.json
      - ./config/quorum/support:/quorum
      - ./config/quorum/networkFiles/validator4:/config/keys
    networks:
      quorum-examples-net:
        ipv4_address: 172.16.239.8

  rpcnode:
    << : *quorum-def
    ports:
      - 8545:8545/tcp
      - 30303
    environment:
      - NODE_ID=5
      - PRIVATE_CONFIG=ignore
      - QUORUM_CONSENSUS=${QUORUM_CONS_ALGO:-istanbul}
    volumes:
      - ./config/quorum/passwords.txt:/config/passwords.txt
      - ./config/quorum/${QUORUM_CONS_ALGO:-istanbul}Genesis.json:/config/genesis.json
      - ./config/quorum/support:/quorum
      - ./config/quorum/networkFiles/member5:/config/keys
    networks:
      quorum-examples-net:
        ipv4_address: 172.16.239.15

{% if privacy %}
  member1tessera:
    << : *tessera-def
    ports:
      - 9081:9080
    environment:
      - PRIVATE_CONFIG=${PRIVATE_CONFIG:-/data/tm.ipc}
      - TESSERA_CONFIG_TYPE="-09"
      - NODE_ID=6
    volumes:
      - ./config/quorum/networkFiles/member1:/config/keys
    networks:
      quorum-examples-net:
        ipv4_address: 172.16.239.21

  member1quorum:
    << : *quorum-def
    ports:
      - 22000:8545/tcp
      - 30303
    depends_on:
      - member1tessera
    environment:
      - NODE_ID=6
      - PRIVATE_CONFIG=ignore
      - QUORUM_CONSENSUS=${QUORUM_CONS_ALGO:-istanbul}
    volumes:
      - ./config/quorum/passwords.txt:/config/passwords.txt
      - ./config/quorum/${QUORUM_CONS_ALGO:-istanbul}Genesis.json:/config/genesis.json
      - ./config/quorum/support:/quorum
      - ./config/quorum/networkFiles/member1:/config/keys
    networks:
      quorum-examples-net:
        ipv4_address: 172.16.239.11

  member2tessera:
    << : *tessera-def
    ports:
      - 9082:9080
    environment:
      - PRIVATE_CONFIG=${PRIVATE_CONFIG:-/data/tm.ipc}
      - TESSERA_CONFIG_TYPE="-09"
      - NODE_ID=7
    volumes:
      - ./config/quorum/networkFiles/member2:/config/keys
    networks:
      quorum-examples-net:
        ipv4_address: 172.16.239.22

  member2quorum:
    << : *quorum-def
    ports:
      - 22001:8545/tcp
      - 30303
{% if privacy %}
    depends_on:
      - member2tessera
{% endif %}
    environment:
      - NODE_ID=7
      - PRIVATE_CONFIG=ignore
      - QUORUM_CONSENSUS=${QUORUM_CONS_ALGO:-istanbul}
    volumes:
      - ./config/quorum/passwords.txt:/config/passwords.txt
      - ./config/quorum/${QUORUM_CONS_ALGO:-istanbul}Genesis.json:/config/genesis.json
      - ./config/quorum/support:/quorum
      - ./config/quorum/networkFiles/member3:/config/keys
    networks:
      quorum-examples-net:
        ipv4_address: 172.16.239.12

  member3tessera:
    << : *tessera-def
    ports:
      - 9083:9080
    environment:
      - PRIVATE_CONFIG=${PRIVATE_CONFIG:-/data/tm.ipc}
      - TESSERA_CONFIG_TYPE="-09"
      - NODE_ID=8
    volumes:
      - ./config/quorum/networkFiles/validator3:/config/keys
    networks:
      quorum-examples-net:
        ipv4_address: 172.16.239.23

  member3quorum:
    << : *quorum-def
    ports:
      - 22002:8545/tcp
      - 30303
    depends_on:
      - member3tessera
    environment:
      - NODE_ID=8
      - PRIVATE_CONFIG=ignore
      - QUORUM_CONSENSUS=${QUORUM_CONS_ALGO:-istanbul}
    volumes:
      - ./config/quorum/passwords.txt:/config/passwords.txt
      - ./config/quorum/${QUORUM_CONS_ALGO:-istanbul}Genesis.json:/config/genesis.json
      - ./config/quorum/support:/quorum
      - ./config/quorum/networkFiles/validator3:/config/keys
    networks:
      quorum-examples-net:
        ipv4_address: 172.16.239.13

{% endif %}

  explorer:
    build: block-explorer-light
    image: quorum-dev-quickstart/block-explorer-light:develop
    depends_on:
      - rpcnode
    ports:
      - 25000:80/tcp
    networks:
      quorum-examples-net:
        ipv4_address: 172.16.239.30

  cakeshop:
    << : *cakeshop-def
    hostname: cakeshop
    ports:
      - "8999:8999"
    volumes:
      - cakeshop:/data
      - ./config/cakeshop:/quorum
    networks:
      quorum-examples-net:
        ipv4_address: 172.16.239.50

networks:
  quorum-examples-net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.239.0/24

volumes:
  cakeshop:
