- kind: Vault
  type: hashicorp
  name: hashicorp-quorum
  specs:
    mount_point: quorum
    address: http://vault:8200
    token: DevVaultToken
    namespace: ''
- kind: Store
  type: key
  name: keystore
  specs:
    vault: hashicorp-quorum
- kind: Store
  type: ethereum
  name: eth-accounts
  specs:
    key_store: keystore
{% if clientType == "goquorum" %}
- kind: Node
  name: quorum-node
  specs:
    rpc:
      addr: http://network_member1quorum_1:8545
    tessera:
      addr: http://network_member1tessera_1:9080
{% else %}
- kind: Node
  name: besu-node
  specs:
    rpc:
      addr: http://network_member1besu_1:8545
{% endif %}
